In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"S:\TATA sales analysis\Online Retail Data Set.csv", encoding="latin1")

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

In [6]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [7]:
(df['CustomerID'].isnull().sum() / len(df)) * 100

np.float64(24.926694334288598)

Removing these records may slightly reduce the total sales captured in the analysis because some transactions could not be linked to specific customers.

In [8]:
df = df.dropna(subset = ['CustomerID'])

In [9]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [10]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [11]:
df.columns

Index(['invoiceno', 'stockcode', 'description', 'quantity', 'invoicedate',
       'unitprice', 'customerid', 'country'],
      dtype='str')

In [12]:
df.duplicated().sum()

np.int64(5225)

In [13]:
df[df.duplicated()]

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,01-12-2010 11:45,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,01-12-2010 11:45,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,01-12-2010 11:45,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,01-12-2010 11:45,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,01-12-2010 11:49,2.95,17920.0,United Kingdom
...,...,...,...,...,...,...,...,...
541675,581538,22068,BLACK PIRATE TREASURE CHEST,1,09-12-2011 11:34,0.39,14446.0,United Kingdom
541689,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,09-12-2011 11:34,2.49,14446.0,United Kingdom
541692,581538,22992,REVOLVER WOODEN RULER,1,09-12-2011 11:34,1.95,14446.0,United Kingdom
541699,581538,22694,WICKER STAR,1,09-12-2011 11:34,2.10,14446.0,United Kingdom
541701,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,09-12-2011 11:34,2.08,14446.0,United Kingdom

invoiceno & customerid is duplicating which is obvious.

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoiceno    406829 non-null  str
 1   stockcode    406829 non-null  str
 2   description  406829 non-null  str
 3   quantity     406829 non-null  int64
 4   invoicedate  406829 non-null  str
 5   unitprice    406829 non-null  float64
 6   customerid   406829 non-null  float64
 7   country      406829 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 27.9 MB

In [15]:
df['invoicedate'] = pd.to_datetime(df['invoicedate'], format= '%d-%m-%Y %H:%M')

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoiceno    406829 non-null  str
 1   stockcode    406829 non-null  str
 2   description  406829 non-null  str
 3   quantity     406829 non-null  int64
 4   invoicedate  406829 non-null  datetime64[us]
 5   unitprice    406829 non-null  float64
 6   customerid   406829 non-null  float64
 7   country      406829 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 27.9 MB

In [17]:
df[df['invoiceno'].astype(str).str.startswith('C')]

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [18]:
df = df[~df['invoiceno'].astype(str).str.startswith('C')]

In [19]:
df[df['invoiceno'].astype(str).str.startswith('C')]

Empty DataFrame
Columns: [invoiceno, stockcode, description, quantity, invoicedate, unitprice, customerid, country]
Index: []

In [20]:
df[df['quantity'] < 0]

Empty DataFrame
Columns: [invoiceno, stockcode, description, quantity, invoicedate, unitprice, customerid, country]
Index: []

In [21]:
df[df['unitprice'] < 0]

Empty DataFrame
Columns: [invoiceno, stockcode, description, quantity, invoicedate, unitprice, customerid, country]
Index: []

In [22]:
df[['quantity', 'unitprice']].describe()

            quantity      unitprice
count  397924.000000  397924.000000
mean       13.021823       3.116174
std       180.420210      22.096788
min         1.000000       0.000000
25%         2.000000       1.250000
50%         6.000000       1.950000
75%        12.000000       3.750000
max     80995.000000    8142.750000

In [23]:
df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.DataFrame'>
Index: 397924 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoiceno    397924 non-null  str
 1   stockcode    397924 non-null  str
 2   description  397924 non-null  str
 3   quantity     397924 non-null  int64
 4   invoicedate  397924 non-null  datetime64[us]
 5   unitprice    397924 non-null  float64
 6   customerid   397924 non-null  float64
 7   country      397924 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 27.3 MB

np.int64(5192)

In [24]:
df['revenue'] = df['quantity'] * df['unitprice']

In [25]:
df.columns

Index(['invoiceno', 'stockcode', 'description', 'quantity', 'invoicedate',
       'unitprice', 'customerid', 'country', 'revenue'],
      dtype='str')

In [26]:
df.to_csv("cleaned_retail_data.csv", index=False)

In [27]:
df[df['unitprice' ] == 0].shape

(40, 9)

In [28]:
df = df[df['unitprice'] > 0]

In [29]:
df.to_csv("cleaned_retail_data.csv", index=False)

In [30]:
df.info()

<class 'pandas.DataFrame'>
Index: 397884 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoiceno    397884 non-null  str
 1   stockcode    397884 non-null  str
 2   description  397884 non-null  str
 3   quantity     397884 non-null  int64
 4   invoicedate  397884 non-null  datetime64[us]
 5   unitprice    397884 non-null  float64
 6   customerid   397884 non-null  float64
 7   country      397884 non-null  str
 8   revenue      397884 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 30.4 MB